// routes/wishlistRoutes.js
// Wishlist routes - handles all wishlist operations for users
// Includes public shared wishlist viewing and protected user wishlist management

const express = require('express');                          // Express router
const wishlistController = require('../controllers/wishlistController'); // Wishlist controller
const { protect, optionalAuth } = require('../middlewares/auth');  // Authentication middleware
const { validate } = require('../middlewares/validate');    // Input validation middleware
const { 
  addToWishlistValidator 
} = require('../utils/validators/wishlistValidator');        // Wishlist validation schemas

const router = express.Router();

// ========== PUBLIC ROUTES ==========
// These routes are accessible without authentication

/**
 * @route   GET /api/wishlist/shared/:token
 * @desc    View a public wishlist by share token
 * @access  Public (no login required)
 * @params  { token } - Unique share token generated by user
 * @returns Wishlist items and owner name
 */
router.get('/shared/:token', wishlistController.getSharedWishlist);

// ========== PROTECTED ROUTES (Authenticated users) ==========
// All routes below require the user to be logged in
router.use(protect);

/**
 * @route   GET /api/wishlist
 * @desc    Get current user's wishlist (creates if doesn't exist)
 * @access  Private (authenticated users only)
 */
router.get('/', wishlistController.getWishlist);

/**
 * @route   POST /api/wishlist/add
 * @desc    Add a product to user's wishlist
 * @access  Private (authenticated users only)
 * @body    { productId, variant: { size, color } }
 */
router.post(
  '/add',
  validate(addToWishlistValidator),  // Validate productId and variant
  wishlistController.addToWishlist
);

/**
 * @route   DELETE /api/wishlist/remove/:productId
 * @desc    Remove a product from wishlist
 * @access  Private (authenticated users only)
 * @params  { productId } - ID of product to remove
 * @body    { variant } - Optional variant to remove specific variant
 */
router.delete('/remove/:productId', wishlistController.removeFromWishlist);

/**
 * @route   DELETE /api/wishlist/clear
 * @desc    Remove all items from wishlist
 * @access  Private (authenticated users only)
 */
router.delete('/clear', wishlistController.clearWishlist);

/**
 * @route   GET /api/wishlist/check/:productId
 * @desc    Check if a specific product is in user's wishlist
 * @access  Private (authenticated users only)
 * @params  { productId } - Product ID to check
 * @returns { inWishlist: boolean, wishlistItemId: string }
 */
router.get('/check/:productId', wishlistController.checkInWishlist);

/**
 * @route   PATCH /api/wishlist/:productId/price-alert
 * @desc    Enable/disable price drop notifications for a wishlist item
 * @access  Private (authenticated users only)
 * @params  { productId } - Product ID
 * @body    { enabled: boolean }
 */
router.patch(
  '/:productId/price-alert',
  wishlistController.setPriceDropAlert
);

/**
 * @route   PATCH /api/wishlist/:productId/restock-alert
 * @desc    Enable/disable restock notifications for a wishlist item
 * @access  Private (authenticated users only)
 * @params  { productId } - Product ID
 * @body    { enabled: boolean }
 */
router.patch(
  '/:productId/restock-alert',
  wishlistController.setRestockAlert
);

/**
 * @route   POST /api/wishlist/share
 * @desc    Generate a shareable token for public wishlist
 * @access  Private (authenticated users only)
 * @returns { shareToken, shareUrl }
 */
router.post('/share', wishlistController.generateShareToken);

/**
 * @route   PATCH /api/wishlist/toggle-public
 * @desc    Make wishlist public or private
 * @access  Private (authenticated users only)
 * @body    { isPublic: boolean }
 */
router.patch('/toggle-public', wishlistController.togglePublicStatus);

module.exports = router;